---

- name: create config folder locally
  file: path=config/{{ ansible_hostname }} state=directory recurse=yes
  become: no
  delegate_to: localhost
  tags:
    - local
  when: global.save_local

- name: create rendered flat-file of neutron network config locally
  template: src=network_config.j2 dest=config/{{ ansible_hostname }}/network_config.sh
  become: no
  delegate_to: localhost
  tags:
    - local
  when: global.save_local


- name: copy neutron configuration script
  template: src=network_config.j2  dest=/tmp/network_config.sh mode='0755'

- name: execute neutron config script
  shell: /tmp/network_config.sh
