---

- name: collect security
  become: no
  command: openstack {{openstack.keystone.admin_credentials}} security group list
  register: _security
  tags:
    - configure

- name: add icmp security rule
  command: openstack {{openstack.keystone.admin_credentials}} security group rule create --proto icmp default
  tags:
    - configure

- name: add ssh security rule
  command: openstack {{openstack.keystone.admin_credentials}} security group rule create --proto tcp --dst-port 22 default
  tags:
    - configure

- name: add icmp security rule for demo user
  command: openstack {{openstack.keystone.demo_credentials}} security group rule create --proto icmp default
  tags:
    - configure

- name: add ssh security rule for demo user
  command: openstack {{openstack.keystone.demo_credentials}} security group rule create --proto tcp --dst-port 22 default
  tags:
    - configure
