
# Install required packages
- name: install packages
  apt: pkg={{item}} state=present
  with_items:
    - keystone
    - python-keystoneclient

# Install and configure Keystone

- name: create a table for keystone
  mysql_db: name=keystone state=present

- name: enable db access 1
  command: mysql -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '{{ openstack.admin_password }}';"

- name: enable db access 2
  command: mysql -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '{{openstack.admin_password}}';"

- name: keystone dbsync
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone

- name: /etc/keystone/keystone.conf
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf
  notify: restart keystone

- name: start keystone
  service: name=keystone state=started

# Add keystone tenants

- name: create admin tenant in keystone
  command: keystone tenant-create --name admin --description "Admin Tenant" --os-token '{{openstack.admin_token}}' --os-endpoint http://controller:35357/v2.0

- name: create admin user
  command: keystone user-create --name admin --pass "{{openstack.admin_password}}" --email "admin@example.com" --os-token '{{openstack.admin_token}}' --os-endpoint http://controller:35357/v2.0

- name: create admin role in keystone
  command: keystone role-create --name admin --os-token '{{openstack.admin_token}}' --os-endpoint http://controller:35357/v2.0

- name: add admin role to tenant and user
  command: keystone user-role-add --user admin --tenant admin --role admin --os-token '{{openstack.admin_token}}' --os-endpoint http://controller:35357/v2.0


- name: create demo tenant in keystone
  command: keystone tenant-create --name demo --description "Demo Tenant" --os-token '{{openstack.admin_token}}' --os-endpoint http://controller:35357/v2.0

- name: create demo user
  command: keystone user-create --name demo --pass "{{openstack.demo_password}}" --email "demo@example.com" --os-token '{{openstack.admin_token}}' --os-endpoint http://controller:35357/v2.0


- name: create service tenant in keystone
  command: keystone tenant-create --name service --description "Service Tenant" --os-token '{{openstack.admin_token}}' --os-endpoint http://controller:35357/v2.0


# Add service entity and endpoints
- name: create keystone service in keystone
  command: keystone service-create --name keystone --type identity --description "Openstack Identity" --os-token '{{openstack.admin_token}}' --os-endpoint http://controller:35357/v2.0

- name: fetch keystone's id
  shell: keystone service-list | awk '/ identity / {print $2}'
  register: _keystone_id

- name: create keystone endpoint in keystone
  command: keystone endpoint-create --service-id {{ _keystone_id }} --publicurl http://controller:5000/v2.0 --internalurl http://controller:5000/v2.0 --adminurl http://controller:35357/v2.0 --region regionOne --os-token '{{openstack.admin_token}}' --os-endpoint http://controller:35357/v2.0
