
# Install and configure Keystone
- name: install packages
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
    allow_unauthenticated: yes
  with_items:
    - keystone
    - apache2
    - libapache2-mod-wsgi
  tags:
    - keystone

- name: create a table for keystone
  mysql_db: name=keystone state=present
  tags:
    - keystone

- name: enable db access 1
  command: mysql -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '{{ openstack.keystone.admin_password }}';"
  tags:
    - keystone

- name: enable db access 2
  command: mysql -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '{{openstack.keystone.admin_password}}';"
  tags:
    - keystone

- name: /etc/keystone/keystone.conf
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf
#  notify: restart keystone
  tags:
    - keystone

- name: keystone dbsync
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
  tags:
    - keystone

- name: configure fernet
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
  tags:
    - keystone

- name: configure credentials
  command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  tags:
    - keystone

- name: Add ServerName to apache
  lineinfile:
    path: /etc/apache2/sites-available/keystone.conf
    insertbefore: '^Listen 5000'
    line: 'ServerName controller'
  notify: restart apache2
  tags:
    - keystone

- name: flush handlers in case of changed config
  meta: flush_handlers
  tags:
    - keystone

# The keystone-manage bootstrap command will create a user, project and role, and will assign the newly created role
# to the newly created user on the newly created project. By default, the names of these new resources will be called
# admin. Optionally, if specified by --bootstrap-public-url, --bootstrap-admin-url and/or --bootstrap-internal-url
# or the equivalent environment variables, the command will create an identity service with the specified
# endpoint information. You may also configure the --bootstrap-region-id and --bootstrap-service-name for
# the endpoints to your deployment’s requirements.
- name: bootstrap identity service
  command: >
    keystone-manage bootstrap --bootstrap-password '{{openstack.keystone.admin_password}}' \
    --bootstrap-admin-url http://controller:35357/v3/ \
    --bootstrap-internal-url http://controller:5000/v3/ \
    --bootstrap-public-url http://controller:5000/v3/ \
    --bootstrap-region-id RegionOne
  tags:
    - keystone


# Collect keystone data to avoid duplication errors
- name: collect services
  command: openstack {{ openstack.keystone.args }} service list
  register: _services
  tags:
    - keystone

- name: collect users
  command: openstack {{ openstack.keystone.args }} user list
  register: _users
  tags:
    - keystone

- name: collect roles
  command: openstack {{ openstack.keystone.args }} role list
  register: _roles
  tags:
    - keystone

- name: collect projects
  command: openstack {{ openstack.keystone.args }} project list
  register: _projects
  tags:
    - keystone

- name: collect domains
  command: openstack {{ openstack.keystone.args }} domain list
  register: _domains
  tags:
    - keystone


# Add keystone services and endpoints
- name: add keystone service
  command: openstack {{openstack.keystone.args}} service create --name keystone --description "Openstack Identity" identity
  when: "'keystone' not in _services.stdout"
  tags:
    - keystone

- name: add keystone endpoints
  command: openstack {{openstack.keystone.args}} endpoint create --region RegionOne identity {{item.a}} http://controller:{{ item.b }}/v3
  with_items:
      - {a: "public", b: 5000}
      - {a: "internal", b: 5000}
      - {a: "admin", b: 35357}
  when: "'keystone' not in _services.stdout"
  tags:
    - keystone

# Create a domain, projects, users, and roles
- name: add default domain
  command: openstack {{openstack.keystone.args}} domain create --description "Default Domain" default
  when: "'default' not in _domains.stdout"
  tags:
    - keystone

- name: add admin project
  command: openstack {{openstack.keystone.args}} project create --domain default --description "Admin project" admin
  when: "'admin' not in _projects.stdout"
  tags:
    - keystone

- name: add admin user
  command: openstack {{openstack.keystone.args}} user create --domain default --password {{openstack.keystone.admin_password}} admin
  when: "'admin' not in _users.stdout"
  tags:
    - keystone

- name: add admin role
  command: openstack {{openstack.keystone.args}} role create admin
  when: "'admin' not in _roles.stdout"
  tags:
    - keystone

- name: add admin role to admin project and user
  command: openstack {{openstack.keystone.args}} role add --project admin --user admin admin
  when: "'admin' not in _users.stdout"
  tags:
    - keystone

- name: add service project
  command: openstack {{openstack.keystone.args}} project create --domain default --description "Service Project" service
  when: "'service' not in _projects.stdout"
  tags:
    - keystone

- name: add demo project
  command: openstack {{openstack.keystone.args}} project create --domain default --description "Demo Project" demo
  when: "'demo' not in _projects.stdout"
  tags:
    - keystone

- name: add demo user
  command: openstack {{openstack.keystone.args}} user create --domain default --password {{openstack.keystone.demo_password}} demo
  when: "'demo' not in _users.stdout"
  tags:
    - keystone

- name: add user role
  command: openstack {{openstack.keystone.args}} role create user
  when: "'user' not in _roles.stdout"
  tags:
    - keystone

- name: add user role to demo project and user
  command: openstack {{openstack.keystone.args}} role add --project demo --user demo user
  when: "'demo' not in _users.stdout"
  tags:
    - keystone
