---

- hosts: server01,server02,server03,server04
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - server-common
    - openstack-common

- hosts: server01
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - mysql
    - rabbitmq
    - memcached
    - etcd
    - openstack-keystone
    - openstack-glance
    - openstack-neutron-controller
    - openstack-nova-controller
    - openstack-horizon
    - openstack-initial-config

- hosts: server02,server03,server04
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - openstack-neutron-compute
    - openstack-nova-compute
