---
- hosts: network
  become: yes
  roles:
  - switch-common

- hosts: leaf
  become: yes
  roles:
  - l3-leaf

- hosts: spine
  become: yes
  roles:
  - l3-spine

- hosts: host
  roles:
  - server-common
  become: true

- hosts: server01
  roles:
  - openstack-controller
  become: true

- hosts: server02
  roles:
  - openstack-compute
  become: true

...
