---

- hosts: HOSTS11,HOSTD12,HOSTD21,HOSTD22
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - openstack-common

- hosts: HOSTS11
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - mysql
    - rabbitmq
    - memcached
    - etcd
    - openstack-keystone
    - openstack-glance
    - openstack-neutron-controller
    - openstack-nova-controller
    - openstack-horizon
    - openstack-initial-config

- hosts: HOSTD12,HOSTD21,HOSTD22
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - openstack-neutron-compute
    - openstack-nova-compute
