---

- hosts: server01,
  user: cumulus
  become: yes
  become_method: sudo
  tasks:

    - name: restart glance
      service: name={{item}} state=restarted
      with_items:
        - glance-api
        - glance-registry
      tags:
        - glance

    - name: start neutron
      service: name={{ item }} state=started enabled=true
      with_items:
          - neutron-server
          - neutron-linuxbridge-agent
          - neutron-dhcp-agent
          - neutron-metadata-agent
          - neutron-l3-agent
      tags:
        - neutron

    - name: restart nova
      service: name={{ item }} state=restarted enabled=true
      with_items:
          - nova-api
          - nova-consoleauth
          - nova-scheduler
          - nova-conductor
          - nova-novncproxy
      tags:
        - nova

- hosts: server02,server03,server04
  user: cumulus
  become: yes
  become_method: sudo
  taskss:
    - name: restart neutron compute
      service: name={{ item }} state=restarted enabled=true
      with_items:
          - neutron-linuxbridge-agent
      tags:
        - neutron

    - name: restart nova
      service: name={{ item }} state=restarted enabled=true
      with_items:
          - nova-compute
      tags:
        - nova

