# Install required packages
- name: get the pike packages
  apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/pike main' state=present

- name: install keyring
  apt: pkg={{item}} state=present
  with_items:
    - ubuntu-cloud-keyring
    - software-properties-common

- name: Update APT
  apt: update_cache=yes

- name: install packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - python-openstackclient

