---

- name: create config folder locally
  file: path=config/{{ ansible_hostname }} state=directory recurse=yes
  become: no
  delegate_to: localhost
  tags:
    - local
  when: global.save_local

# Install required packages
- name: install packages
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
    allow_unauthenticated: yes
  with_items:
    - neutron-linuxbridge-agent
  tags:
    - neutron


- name: create rendered flat-file of neutron configurations locally
  template: src=network_config.j2 dest=config/{{ ansible_hostname }}/{{item}}
  become: no
  delegate_to: localhost
  tags:
    - local
  with_items:
      - neutron.conf
      - linuxbridge_agent.ini
  when: global.save_local


# Configure Neutron
- name: neutron config files
  template: src={{item}}.j2 dest=/etc/neutron/{{item}}
  with_items:
      - neutron.conf
  notify: restart neutron
  tags:
    - neutron

- name: ml2 config files
  template: src={{item}}.j2 dest=/etc/neutron/plugins/ml2/{{item}}
  with_items:
      - linuxbridge_agent.ini
  notify: restart neutron
  tags:
    - neutron

- name: flush handlers in case of changed config
  meta: flush_handlers
  tags:
    - neutron

- name: start neutron compute
  service: name={{ item }} state=started enabled=true
  with_items:
      - neutron-linuxbridge-agent
  tags:
    - neutron

- name: wait for neutron to wake up
  pause: seconds=10
  tags:
    - neutron
