
# Install required packages
- name: install packages
  apt: pkg={{item}} state=present
  with_items:
    - mysql-server
    - mysql-client-5.5

- name: make sure mysql is running
  service: name=mysql state=started
