
# Install required packages
- name: install packages
  apt:
    pkg: {{item}}
    state: present
    update_cache: yes
    allow_unauthenticated: yes
  with_items:
    - openstack-dashboard
  tags:
    - horizon


- name: horizon config files
  template: src={{item}}.j2 dest=/etc/openstack-dashboard/{{item}}
  with_items:
      - local_settings.py
  notify: restart apache2
  tags:
    - horizon

- name: Add WSGI line to horizon apache config
  lineinfile:
    path: /etc/apache2/conf-available/openstack-dashboard.conf
    insertafter: "^WSGIProcessGroup*"
    line: 'WSGIApplicationGroup %{GLOBAL}'
  notify: restart apache2
  tags:
    - horizon

- name: flush handlers in case of changed config
  meta: flush_handlers
  tags:
    - horizon

