
# This handler reloads ifupdown2, which comes standard on cumulus switches.
# ifupdown2 is much smarter than its predecessor and as such reloading is painless.
# Note that the -a means "auto" - this command only reloads interfaces that are
# marked with the auto keyword.
- name: reload networking
  command: ifreload -a

# This handler attempts to reload legacy ifupdown. However, when making substantial
# changes to the networking stack such as changing routes, etc, sometimes this
# command fails and the only solution is to reboot the server.
- name: reload networking legacy
  shell: ifdown --force -a && ifup --force -a
