
# Install required packages
- name: install packages
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
    allow_unauthenticated: yes
  with_items:
    - glance
  tags:
    - glance

# Install and configure Glance
- name: create a table for glance
  mysql_db: name=glance state=present
  tags:
    - glance

- name: enable db access 1
  command: mysql -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '{{ openstack.keystone.admin_password }}';"
  tags:
    - glance

- name: enable db access 2
  command: mysql  -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '{{openstack.keystone.admin_password}}';"
  tags:
    - glance

- name: glance config files
  template: src={{item}}.j2 dest=/etc/glance/{{item}}
  with_items:
      - glance-api.conf
      - glance-registry.conf
  notify: restart glance
  tags:
    - glance

- name: glance dbsync
  shell: su -s /bin/sh -c "glance-manage db_sync" glance
  tags:
    - glance

- name: flush handlers in case of changed config
  meta: flush_handlers
  tags:
    - glance

- name: start glance api
  service: name=glance-api state=started
  tags:
    - glance

- name: start glance regisry
  service: name=glance-registry state=started
  tags:
    - glance

- name: wait for glance to wake up
  pause: seconds=10
  tags:
    - glance

# Create glance user, service, and endpoint
- name: collect services
  command: openstack {{ openstack.keystone.args }} service list
  register: _services
  tags:
    - glance

- name: collect users
  command: openstack {{ openstack.keystone.args }} user list
  register: _users
  tags:
    - glance

- name: collect roles
  command: openstack {{ openstack.keystone.args }} role list
  register: _roles
  tags:
    - glance

- name: collect projects
  command: openstack {{ openstack.keystone.args }} project list
  register: _projects
  tags:
    - glance

- name: collect domains
  command: openstack {{ openstack.keystone.args }} domain list
  register: _domains
  tags:
    - glance

- name: add glance user
  command: openstack {{openstack.keystone.args}} user create --domain default --password {{openstack.keystone.admin_password}} glance
  when: "'glance' not in _users.stdout"
  tags:
    - glance

- name: add admin role to glance user
  command: openstack {{openstack.keystone.args}} role add --project service --user glance admin
  when: "'glance' not in _users.stdout"
  tags:
    - glance

- name: add glance service
  command: openstack {{openstack.keystone.args}} service create --name glance --description "Openstack Image" image
  when: "'glance' not in _services.stdout"
  tags:
    - glance

- name: add glance endpoints
  command: openstack {{openstack.keystone.args}} endpoint create --region RegionOne image {{item.a}} http://controller:{{ item.b }}
  with_items:
      - {a: "public", b: 9292}
      - {a: "internal", b: 9292}
      - {a: "admin", b: 9292}
  when: "'glance' not in _services.stdout"
  tags:
    - glance

- name: wait for glance to wake up
  pause: seconds=10
  tags:
    - glance


# Now add a basic image.

- name: collect images
  command: openstack {{ openstack.keystone.admin_credentials }} image list
  register: _images
  tags:
    - glance

- name: download cirros.conf
  get_url:
    url: http://download.cirros-cloud.net/0.3.3/cirros-0.3.3-x86_64-disk.img
    dest: /tmp/
    mode: 0440
  when: "'cirros' not in _images.stdout"
  tags:
    - glance

- name: create the cirros image
  command: openstack {{ openstack.keystone.admin_credentials }} image create "cirros" --file /tmp/cirros-0.3.3-x86_64-disk.img  --disk-format qcow2 --container-format bare --public
  when: "'cirros' not in _images.stdout"
  tags:
    - glance
