---

# Install required packages
- name: install packages
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
    allow_unauthenticated: yes
  with_items:
    - nova-compute
  tags:
    - nova

- name: verify node supports hardware acceleration
  become: yes
  command: "egrep -c '(vmx|svm)' /proc/cpuinfo"
  register: hw_acceleration
  tags:
    - nova

- set_fact:
    hw_accelerated: true
  when: "{{ hw_acceleration.stdout }} >= 1"
  tags:
    - nova

- name: nova config files
  template: src={{item}}.j2 dest=/etc/nova/{{item}}
  with_items:
      - nova.conf
      - nova-compute.conf
  notify: restart nova compute
  tags:
    - nova

- name: flush handlers in case of changed config
  meta: flush_handlers
  tags:
    - nova

- name: start nova compute
  service: name={{ item }} state=started enabled=true
  with_items:
      - nova-compute
  tags:
    - nova

- name: wait for nova to wake up
  pause: seconds=10
  tags:
    - nova

