#!/bin/bash


openstack --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin --os-password CumulusLinux --os-auth-url http://controller:35357/v3 --os-identity-api-version 3 --os-image-api-version 2 address scope create  --ip-version 4  --share  address_scope_ip4
openstack --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin --os-password CumulusLinux --os-auth-url http://controller:35357/v3 --os-identity-api-version 3 --os-image-api-version 2 address scope create  --ip-version 6  --share  address_scope_ip6

openstack --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin --os-password CumulusLinux --os-auth-url http://controller:35357/v3 --os-identity-api-version 3 --os-image-api-version 2 subnet pool create  --default  --default-prefix-length 64  --address-scope address_scope_ip6  --pool-prefix 2001:dead:beef::/48  --share  subnet_pool_ip6
openstack --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin --os-password CumulusLinux --os-auth-url http://controller:35357/v3 --os-identity-api-version 3 --os-image-api-version 2 subnet pool create  --default  --default-prefix-length 24  --address-scope address_scope_ip4  --pool-prefix 10.1.0.0/16  --share  subnet_pool_ip4

openstack --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin --os-password CumulusLinux --os-auth-url http://controller:35357/v3 --os-identity-api-version 3 --os-image-api-version 2 network create  --project admin  --provider-physical-network provider  --provider-segment 1004  --provider-network-type vlan  net4
openstack --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin --os-password CumulusLinux --os-auth-url http://controller:35357/v3 --os-identity-api-version 3 --os-image-api-version 2 network create  --project admin  --provider-physical-network provider  --provider-segment 1003  --provider-network-type vlan  net3
openstack --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin --os-password CumulusLinux --os-auth-url http://controller:35357/v3 --os-identity-api-version 3 --os-image-api-version 2 network create  --default \  --provider-physical-network provider  --share \  --provider-network-type flat  public

openstack --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin --os-password CumulusLinux --os-auth-url http://controller:35357/v3 --os-identity-api-version 3 --os-image-api-version 2 subnet create  --prefix-length 24  --network public  --dns-nameserver 8.8.8.8  --subnet-pool subnet_pool_ip4  --ip-version 4  --gateway 10.1.1.1  public_ipv4
openstack --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin --os-password CumulusLinux --os-auth-url http://controller:35357/v3 --os-identity-api-version 3 --os-image-api-version 2 subnet create  --allocation-pool start=10.1.103.101,end=10.1.103.199  --subnet-range 10.1.103.0/24  --network net3  --gateway 10.1.103.1  subnet3_ipv4
openstack --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin --os-password CumulusLinux --os-auth-url http://controller:35357/v3 --os-identity-api-version 3 --os-image-api-version 2 subnet create  --allocation-pool start=10.1.104.101,end=10.1.104.199  --subnet-range 10.1.104.0/24  --network net4  --gateway 10.1.104.1  subnet4_ipv4
